services:
  backend-prod:
    image: adalmia/sensai-ai:latest
    working_dir: /src
    command: bash -c "python /src/startup.py && uvicorn api.main:app --host 0.0.0.0 --port 8001"
    volumes:
      - /appdata_prod:/appdata
    ports:
      - "8001:8001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    restart: unless-stopped
    networks:
      - sensai-network-prod

  cron-prod:
    image: adalmia/sensai-ai:latest
    working_dir: /src
    command: sh -c "apt-get update && apt-get install -y cron && echo '55 23 * * * cd /src && /usr/local/bin/python -c \"from api.cron import send_usage_summary_stats; import asyncio; asyncio.run(send_usage_summary_stats())\" >> /appdata/logs/backend-cron.log 2>&1' >> /src/sensai-cron && echo '0 10 * * * cd /src && /usr/local/bin/python -c \"from api.bq.cron import run_all_syncs; import asyncio; asyncio.run(run_all_syncs())\" >> /appdata/logs/backend-cron.log 2>&1' >> /src/sensai-cron && crontab /src/sensai-cron && cron -f"
    volumes:
      - /appdata_prod:/appdata
    environment:
      - TZ=Asia/Kolkata
    restart: unless-stopped

networks:
  sensai-network-prod:
    driver: bridge
